apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: ${namespace}
spec:
  serviceAccountName: ${service_account_name}
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  scrapeInterval: 15s
  evaluationInterval: 15s
  additionalScrapeConfigs:
    name: additional-scrape-config
    key: additional-scrape-config.yaml
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false